site_name: e100学习手册
site_url: https://uav-wiki.page.dev
theme:
  name: material

nav:
  - 概览:
      - 首页: index.md
  - 基础入门:
      - 无人机硬件基础: hardware.md
      - 四旋翼数学基础: math.md
  - 快速开始: quickstart.md
  - 进阶开发:
      - 二次开发指南:
          - 文档总览: sd-document/index.md
          - LubanCat 机载电脑: sd-document/lubancat.md
          - MCU 开发指南: sd-document/mcu.md
          - UART 通信节点: sd-document/uart-tx-node.md
